apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: opsmx11/docker-swarm-production
  newTag: 5e7f1a7-160
- name: opsmxssd/docker-swarm-production
  newTag: 5e7f1a7-162
