apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-service
  name: mongo-service
spec:
  selector:
    matchLabels:
      app: mongo-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mongo-service
        ssd.admissionreview.accountname: staging
        ssd.admissionreview.appname: mongo-service
    spec:
      containers:
      - name: mongo-service
        image: opsmx11/mongo-service-staging:0a9bde1-22
