apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-service
  name: mongo-service
spec:
  selector:
    matchLabels:
      app: mongo-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mongo-service
        ssd.admissionreview.accountname: dev
        ssd.admissionreview.appname: mongo-service-dev
    spec:
      containers:
      - name: mongo-service
        image: opsmxssd/mongo-service-dev:0a9bde1-28
