apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scout-service
  name: scout-service
spec:
  selector:
    matchLabels:
      app: scout-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: scout-service
        ssd.admissionreview.accountname: dev
        ssd.admissionreview.appname: scout-service-dev
    spec:
      containers:
      - name: scout-service
        image: opsmx11/scout-service-dev:a5c60f0-5
