apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: detection-service
  name: detection-service
spec:
  selector:
    matchLabels:
      app: detection-service
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: detection-service
        ssd.admissionreview.accountname: dev
        ssd.admissionreview.appname: detection-service-dev
    spec:
      containers:
      - name: detection-service
        image: opsmx11/detection-service-dev:4ed8813-1
